## **NBA Analysis and Machine Learning**
#### Purpose: In order to better understand the NBA as a whole, we took a deep dive into the general offensive and defensive team stats from the last 20 years. These stats then allowed us to build an machine learning program to try and predict the NBA finals champion.
## **Cleaning the Data**

In [ ]:
# Initialize spark environment
import os
# Find the latest version of spark 3.0  from http://www-us.apache.org/dist/spark/ and enter as the spark version
# For example:
spark_version = 'spark-3.0.2'
os.environ['SPARK_VERSION']=spark_version

# Install Spark and Java
!apt-get update
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q http://www-us.apache.org/dist/spark/$SPARK_VERSION/$SPARK_VERSION-bin-hadoop2.7.tgz
!tar xf $SPARK_VERSION-bin-hadoop2.7.tgz
!pip install -q findspark

# Set Environment Variables
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = f"/content/{spark_version}-bin-hadoop2.7"

# Start a SparkSession
import findspark
findspark.init()

Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release
Hit:7 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:8 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:9 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Get:10 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Hit:13 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Fetched 252 kB in 3s (100 kB/s)
Reading package lists... Done

In [ ]:
!wget https://jdbc.postgresql.org/download/postgresql-42.2.9.jar

--2021-02-27 01:03:17--  https://jdbc.postgresql.org/download/postgresql-42.2.9.jar
Resolving jdbc.postgresql.org (jdbc.postgresql.org)... 72.32.157.228, 2001:4800:3e1:1::228
Connecting to jdbc.postgresql.org (jdbc.postgresql.org)|72.32.157.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 914037 (893K) [application/java-archive]
Saving to: ‘postgresql-42.2.9.jar.1’

postgresql-42.2.9.j 100%[===================>] 892.61K  --.-KB/s    in 0.1s

2021-02-27 01:03:18 (6.08 MB/s) - ‘postgresql-42.2.9.jar.1’ saved [914037/914037]

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("CloudETL").config("spark.driver.extraClassPath","/content/postgresql-42.2.9.jar").getOrCreate()

In [ ]:
# Import Team stats from the last 20 years 
from pyspark import SparkFiles
# Load in employee.csv from S3 into a DataFrame
url = "https://nbadatabasebucket.s3.amazonaws.com/Team_00-20.csv"
spark.sparkContext.addFile(url)

df = spark.read.option('header', 'true').csv(SparkFiles.get("Team_00-20.csv"), inferSchema=True, sep=',', timestampFormat="mm/dd/yy")
df.show(10)

+----+--------------------+---+-----+----+----+-----+---+----+-----+----+----+-----+----+----+-----+----+----+----+----+----+---+----+----+-----+--------+------------+
|Year|                Team|  G|   MP|  FG| FGA|  FG%| 3P| 3PA|  3P%|  2P| 2PA|  2P%|  FT| FTA|  FT%| ORB| DRB| TRB| AST| STL|BLK| TOV|  PF|  PTS|Playoffs|Championship|
+----+--------------------+---+-----+----+----+-----+---+----+-----+----+----+-----+----+----+-----+----+----+----+----+----+---+----+----+-----+--------+------------+
|2000|    Sacramento Kings| 82|20080|39.7|88.2|0.449|6.1|17.1|0.354|33.6|71.1|0.472|20.3|26.3|0.771|12.5|34.2|46.7|23.4|10.0|5.5|15.5|20.2|105.6|    true|       false|
|2000|     Milwaukee Bucks| 82|19780|41.0|89.5|0.458|7.4|19.5|0.379|33.6|70.0| 0.48|19.4|24.7|0.787|12.8|32.9|45.8|24.3| 8.8|5.1|14.8|25.4|108.8|    true|       false|
|2000|  Los Angeles Lakers| 82|19905|40.9|87.9|0.465|5.8|16.8|0.344|35.1|71.1|0.494|20.9|30.7|0.683|14.3|33.9|48.2|24.8| 7.4|6.4|15.6|24.6|108.4|    true|        true|
|2000|    Dallas Mavericks| 82|19805|40.1|87.3|0.459|6.7|17.6|0.381|33.4|69.7|0.479|20.2|25.4|0.794|10.8|33.4|44.2|22.6| 8.0|6.4|14.8|24.8|107.1|    true|       false|
|2000|     Toronto Raptors| 82|19955|40.3|92.2|0.437|5.7|15.4|0.369|34.6|76.8|0.451|19.6|26.2|0.747|14.8|33.4|48.2|26.5| 7.9|6.9|14.3|23.1|105.9|    true|       false|
|2000|       Orlando Magic| 82|19955|38.9|88.7|0.438|6.3|17.4|0.364|32.6|71.4|0.456|19.1|26.7|0.714|13.8|31.6|45.4|23.3| 8.7|6.2|16.1|26.7|103.2|    true|       false|
|2000|Minnesota Timberw...| 82|19830|41.5|90.5|0.458|4.2|11.9|0.357|37.2|78.7|0.473|18.0|22.9|0.785|13.2|32.6|45.8|27.5| 9.0|6.0|15.0|25.0|105.2|    true|       false|
|2000| Seattle SuperSonics| 82|19805|40.1|88.0|0.456|6.2|15.5|0.399|33.9|72.5|0.468|19.2|26.3|0.732|13.2|32.1|45.3|23.7| 8.7|5.4|16.6|22.9|105.6|   false|       false|
|2000|     Houston Rockets| 82|19830|39.4|86.9|0.453|6.7|18.9|0.357|32.7|68.0| 0.48|21.2|27.9|0.758|12.3|33.8|46.1|21.6| 7.9|4.8|16.1|22.2|106.7|   false|       false|
|2000|           Utah Jazz| 82|19780|40.0|85.0|0.471|4.4|11.5|0.381|35.6|73.5|0.485|23.2|30.8|0.752|12.7|32.2|45.0|28.5| 8.9|6.3|17.5|28.5|107.6|    true|       false|
+----+--------------------+---+-----+----+----+-----+---+----+-----+----+----+-----+----+----+-----+----+----+----+----+----+---+----+----+-----+--------+------------+
only showing top 10 rows

In [ ]:
# Import opposing team stats from the last 20 years
from pyspark import SparkFiles
# Load in employee.csv from S3 into a DataFrame
url = "https://nbadatabasebucket.s3.amazonaws.com/Opp_00-20.csv"
spark.sparkContext.addFile(url)

df2 = spark.read.option('header', 'true').csv(SparkFiles.get("Opp_00-20.csv"), inferSchema=True, sep=',', timestampFormat="mm/dd/yy")
df2.show(10)

+----+--------------------+---+-----+----+----+-----+---+----+-----+----+----+-----+----+----+-----+----+----+----+----+---+---+----+----+-----+---------+------------+
|Year|                Team|  G|   MP|  FG| FGA|  FG%| 3P| 3PA|  3P%|  2P| 2PA|  2P%|  FT| FTA|  FT%| ORB| DRB| TRB| AST|STL|BLK| TOV|  PF|  PTS|Playoffs2|Championship|
+----+--------------------+---+-----+----+----+-----+---+----+-----+----+----+-----+----+----+-----+----+----+----+----+---+---+----+----+-----+---------+------------+
|2000|     New York Knicks| 82|19905|35.7|85.7|0.417|6.2|17.6|0.352|29.5|68.1|0.434|20.6|28.0|0.733|12.1|33.6|45.8|21.9|8.3|4.7|16.9|24.4| 98.2|     true|       false|
|2000|          Miami Heat| 82|19880|37.4|86.8|0.431|5.0|15.1|0.331|32.5|71.7|0.452|18.6|25.2|0.737|12.7|35.0|47.7|19.7|8.3|5.9|17.7|25.3| 98.5|     true|       false|
|2000|   San Antonio Spurs| 82|19830|38.3|91.5|0.419|4.6|14.1|0.329|33.7|77.4|0.435|16.7|22.5|0.741|13.1|32.9|45.9|21.8|8.1|5.8|15.0|26.3| 98.0|     true|       false|
|2000|   Charlotte Hornets| 82|19880|37.4|87.8|0.426|5.3|14.6| 0.36|32.1|73.2|0.439|19.5|25.8|0.756|12.0|32.9|44.9|23.6|8.3|5.1|16.3|23.9| 99.5|     true|       false|
|2000|  Philadelphia 76ers| 82|19855|38.3|89.4|0.429|5.7|16.7|0.342|32.6|72.7|0.448|16.6|22.1|0.749|13.1|31.6|44.7|23.6|9.0|6.1|16.8|25.9| 98.9|     true|       false|
|2000|Portland Trail Bl...| 82|19780|38.4|87.6|0.438|5.5|15.0|0.368|32.8|72.6|0.452|19.5|26.3|0.744|12.9|30.5|43.3|23.8|8.8|4.4|16.6|23.7|101.8|     true|       false|
|2000|        Phoenix Suns| 82|19805|36.3|83.6|0.435|4.3|12.2|0.349|32.1|71.4|0.449|21.1|27.7|0.761|11.7|33.7|45.4|21.5|8.9|5.4|18.6|23.7| 98.0|     true|       false|
|2000|           Utah Jazz| 82|19780|36.1|82.1|0.439|5.5|16.1|0.343|30.5|66.0|0.462|24.7|32.3|0.765|11.8|29.5|41.3|21.1|9.4|6.1|17.8|27.1|102.4|     true|       false|
|2000|      Indiana Pacers| 82|19980|38.0|89.8|0.423|5.1|15.1|0.336|32.9|74.7|0.441|21.1|27.9|0.758|14.0|33.5|47.5|22.8|7.9|5.2|15.0|25.3|102.2|     true|       false|
|2000|     Houston Rockets| 82|19830|40.4|90.1|0.449|4.8|13.6|0.354|35.6|76.6|0.465|18.5|24.9|0.744|13.2|32.4|45.6|23.2|8.1|5.4|14.6|23.7|104.2|    false|       false|
+----+--------------------+---+-----+----+----+-----+---+----+-----+----+----+-----+----+----+-----+----+----+----+----+---+---+----+----+-----+---------+------------+
only showing top 10 rows

In [ ]:
# Convert spark df to pandas df for ease of opperation
import pandas as pd
Team_DF = df.toPandas()
Opp_DF = df2.toPandas()
Team_DF.head()

   Year                Team   G     MP  ...    PF    PTS  Playoffs  Championship
0  2000    Sacramento Kings  82  20080  ...  20.2  105.6      True         False
1  2000     Milwaukee Bucks  82  19780  ...  25.4  108.8      True         False
2  2000  Los Angeles Lakers  82  19905  ...  24.6  108.4      True          True
3  2000    Dallas Mavericks  82  19805  ...  24.8  107.1      True         False
4  2000     Toronto Raptors  82  19955  ...  23.1  105.9      True         False

[5 rows x 27 columns]

## **Machine Learning**

### Set up: forming Cause & Effect DFs and performing a Test / Train Split

In [ ]:
# removing Effect columns to form a Cause DF
team_X = Team_DF.drop(columns=["Playoffs", "Championship"])
team_X

     Year                   Team   G     MP    FG  ...   STL  BLK   TOV    PF    PTS
0    2000       Sacramento Kings  82  20080  39.7  ...  10.0  5.5  15.5  20.2  105.6
1    2000        Milwaukee Bucks  82  19780  41.0  ...   8.8  5.1  14.8  25.4  108.8
2    2000     Los Angeles Lakers  82  19905  40.9  ...   7.4  6.4  15.6  24.6  108.4
3    2000       Dallas Mavericks  82  19805  40.1  ...   8.0  6.4  14.8  24.8  107.1
4    2000        Toronto Raptors  82  19955  40.3  ...   7.9  6.9  14.3  23.1  105.9
..    ...                    ...  ..    ...   ...  ...   ...  ...   ...   ...    ...
591  2019        New York Knicks  66  15965  40.2  ...   7.7  4.8  14.4  22.3  106.5
592  2019    Cleveland Cavaliers  65  15725  40.5  ...   6.9  3.3  16.6  18.4  107.5
593  2019          Chicago Bulls  65  15675  39.5  ...  10.0  4.1  15.4  21.8  106.7
594  2019  Golden State Warriors  65  15725  38.2  ...   8.1  4.5  14.7  19.8  105.2
595  2019      Charlotte Hornets  65  15750  38.6  ...   6.8  4.3  15.1  19.5  106.3

[596 rows x 25 columns]

In [ ]:
# In order to push data frame to machine learning all strings must be removed
# therefore we add a label encoder to match every team to a integer.

from sklearn.preprocessing import LabelEncoder
team_encoder = LabelEncoder()
team_encoder.fit(team_X["Team"])
team_X["Team"] = team_encoder.transform(team_X["Team"])
team_X

     Year  Team   G     MP    FG   FGA  ...   AST   STL  BLK   TOV    PF    PTS
0    2000    29  82  20080  39.7  88.2  ...  23.4  10.0  5.5  15.5  20.2  105.6
1    2000    17  82  19780  41.0  89.5  ...  24.3   8.8  5.1  14.8  25.4  108.8
2    2000    14  82  19905  40.9  87.9  ...  24.8   7.4  6.4  15.6  24.6  108.4
3    2000     7  82  19805  40.1  87.3  ...  22.6   8.0  6.4  14.8  24.8  107.1
4    2000    32  82  19955  40.3  92.2  ...  26.5   7.9  6.9  14.3  23.1  105.9
..    ...   ...  ..    ...   ...   ...  ...   ...   ...  ...   ...   ...    ...
591  2019    23  66  15965  40.2  89.9  ...  22.2   7.7  4.8  14.4  22.3  106.5
592  2019     6  65  15725  40.5  88.4  ...  23.2   6.9  3.3  16.6  18.4  107.5
593  2019     5  65  15675  39.5  88.5  ...  23.2  10.0  4.1  15.4  21.8  106.7
594  2019    10  65  15725  38.2  87.2  ...  25.3   8.1  4.5  14.7  19.8  105.2
595  2019     4  65  15750  38.6  88.8  ...  24.6   6.8  4.3  15.1  19.5  106.3

[596 rows x 25 columns]

In [ ]:
# Split teams_X into train df
team_X_train = team_X[team_X["Year"] < 2019 ]
team_X_train

     Year  Team   G     MP    FG   FGA  ...   AST   STL  BLK   TOV    PF    PTS
0    2000    29  82  20080  39.7  88.2  ...  23.4  10.0  5.5  15.5  20.2  105.6
1    2000    17  82  19780  41.0  89.5  ...  24.3   8.8  5.1  14.8  25.4  108.8
2    2000    14  82  19905  40.9  87.9  ...  24.8   7.4  6.4  15.6  24.6  108.4
3    2000     7  82  19805  40.1  87.3  ...  22.6   8.0  6.4  14.8  24.8  107.1
4    2000    32  82  19955  40.3  92.2  ...  26.5   7.9  6.9  14.3  23.1  105.9
..    ...   ...  ..    ...   ...   ...  ...   ...   ...  ...   ...   ...    ...
561  2018    16  82  19730  40.3  89.4  ...  24.7   7.8  5.5  15.0  21.2  107.3
562  2018     5  82  19905  39.8  87.8  ...  21.9   7.3  4.3  14.1  20.3  104.8
563  2018    23  82  19780  38.2  88.2  ...  20.1   6.8  5.1  14.0  20.9  104.5
564  2018     6  82  19755  40.1  90.3  ...  21.3   6.7  2.5  13.9  20.6  107.7
565  2018    15  82  19880  38.9  86.5  ...  24.5   8.5  5.6  14.3  22.5  106.1

[566 rows x 25 columns]

In [ ]:
# Split team_X into test df
team_X_test = team_X[team_X["Year"] == 2019 ]
# Create results dataframe to push predictions to match teams to predictions
team_results = team_X_test[["Year", "Team"]]
team_results2 = team_X_test[["Year", "Team"]]
team_results["Team"] = team_encoder.inverse_transform(team_results["Team"])
team_results2["Team"] = team_encoder.inverse_transform(team_results2["Team"])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [ ]:
#removing Cause columns to form a Effect DF for playoffs
team_playoffs = Team_DF[["Year","Playoffs"]]
team_playoffs

     Year  Playoffs
0    2000      True
1    2000      True
2    2000      True
3    2000      True
4    2000      True
..    ...       ...
591  2019     False
592  2019     False
593  2019     False
594  2019     False
595  2019     False

[596 rows x 2 columns]

In [ ]:
# In order to push data frame to machine learning all boolean values must be removed
# therefore we add a label encoder to match true and false to 1 & 0.
from sklearn.preprocessing import LabelEncoder
result_encoder = LabelEncoder()
team_playoffs = Team_DF[["Year","Playoffs"]]
result_encoder.fit(team_playoffs["Playoffs"])
team_playoffs["Playoffs"] = result_encoder.transform(team_playoffs["Playoffs"])
team_playoffs

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

     Year  Playoffs
0    2000         1
1    2000         1
2    2000         1
3    2000         1
4    2000         1
..    ...       ...
591  2019         0
592  2019         0
593  2019         0
594  2019         0
595  2019         0

[596 rows x 2 columns]

In [ ]:
# Split effect dfs into train and split effect dfs
team_playoffs_train = team_playoffs[team_playoffs["Year"] < 2019]
team_playoffs_test = team_playoffs[team_playoffs["Year"] == 2019]
team_playoffs_test

     Year  Playoffs
566  2019         1
567  2019         1
568  2019         1
569  2019         1
570  2019         1
571  2019         0
572  2019         0
573  2019         0
574  2019         0
575  2019         1
576  2019         1
577  2019         1
578  2019         1
579  2019         0
580  2019         1
581  2019         1
582  2019         1
583  2019         1
584  2019         1
585  2019         1
586  2019         0
587  2019         1
588  2019         0
589  2019         0
590  2019         0
591  2019         0
592  2019         0
593  2019         0
594  2019         0
595  2019         0

In [ ]:
# Removing Cause columns to form a Effect DF for championship
# Changing boolean values to 1 & 0
team_champ = Team_DF[["Year","Championship"]]
team_champ["Championship"] = result_encoder.transform(team_champ["Championship"])
team_champ

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

     Year  Championship
0    2000             0
1    2000             0
2    2000             1
3    2000             0
4    2000             0
..    ...           ...
591  2019             0
592  2019             0
593  2019             0
594  2019             0
595  2019             0

[596 rows x 2 columns]

In [ ]:
# Split effect dfs into train and split effect dfs
team_champ_train = team_champ[team_champ["Year"] < 2019]
team_champ_test = team_champ[team_champ["Year"] == 2019]
team_champ_test

     Year  Championship
566  2019             0
567  2019             0
568  2019             0
569  2019             0
570  2019             0
571  2019             0
572  2019             0
573  2019             0
574  2019             0
575  2019             0
576  2019             0
577  2019             0
578  2019             0
579  2019             0
580  2019             0
581  2019             1
582  2019             0
583  2019             0
584  2019             0
585  2019             0
586  2019             0
587  2019             0
588  2019             0
589  2019             0
590  2019             0
591  2019             0
592  2019             0
593  2019             0
594  2019             0
595  2019             0

In [ ]:
# Drop the Year column
team_X_test = team_X_test.drop(columns = ["Year"])
team_X_train = team_X_train.drop(columns = ["Year"])
team_playoffs_test = team_playoffs_test.drop(columns = ["Year"])
team_playoffs_train = team_playoffs_train.drop(columns = ["Year"])
team_champ_test = team_champ_test.drop(columns = ["Year"])
team_champ_train = team_champ_train.drop(columns = ["Year"])

In [ ]:
# Reshape playoffs and champ dbs
team_playoffs_test_values = team_playoffs_test["Playoffs"].values.reshape(-1,1)
team_playoffs_train_values = team_playoffs_train["Playoffs"].values.reshape(-1,1)
team_champ_test_values = team_champ_test["Championship"].values.reshape(-1,1)
team_champ_train_values = team_champ_train["Championship"].values.reshape(-1,1)
print(team_playoffs_test_values.shape, team_playoffs_train_values.shape, team_champ_test_values.shape, team_champ_train_values.shape, team_X_test.shape, team_X_train.shape  )

(30, 1) (566, 1) (30, 1) (566, 1) (30, 24) (566, 24)

In [ ]:
print(team_playoffs_test_values.shape, team_playoffs_train_values.shape, team_champ_test_values.shape, team_champ_train_values.shape, team_X_test.shape, team_X_train.shape  )

(30, 1) (566, 1) (30, 1) (566, 1) (30, 24) (566, 24)

In [ ]:
from sklearn.preprocessing import StandardScaler

team_X_scaler = StandardScaler().fit(team_X_train)
team_playoffs_scaler = StandardScaler().fit(team_playoffs_train_values)
team_champ_scaler = StandardScaler().fit(team_champ_train_values)

### Linear Regression Model Machine Learning

In [ ]:

# import and fit linear regression models for playoffs and championship data
from sklearn.linear_model import LinearRegression
linear_playoff_model = LinearRegression()
linear_champ_model = LinearRegression()
linear_playoff_model.fit(team_X_train, team_playoffs_train_values)
linear_champ_model.fit(team_X_train, team_champ_train_values)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
# convert tuple of tuple into list to move to results
from itertools import chain
champ_predictions = linear_champ_model.predict(team_X_test)
champ_prediction = [x for x in chain.from_iterable(champ_predictions)]
print(champ_prediction)

[0.06513860143190264, 0.16524553197714908, 0.10763573965199491, -0.00020062596018277645, 0.078474340407519, 0.07741280314816201, 0.08160077481569594, 0.01919744190279893, 0.06204630191977856, 0.11475956374663276, 0.11157978144074931, 0.0544666935102196, 0.1504674654098732, 0.11093505933887648, 0.13680533212737167, 0.1452099311851356, -0.0037518061129571123, 0.08947158331808858, 0.12037907586218033, 0.08274417530248535, 0.0049438040383851245, 0.017359943781405818, 0.001177653752044705, -0.027663552246972145, -0.0006981813190094499, -0.012066466495122441, -0.024490889955949058, 0.044924248189735394, -0.017440496765727787, -0.029370017491906708]

In [ ]:
# make the max value true and all other values false to predict championship
champ_max = max(champ_prediction)
champ_prediction_bool = []
for i in champ_prediction:
  if i == champ_max:
    champ_prediction_bool.append(True)
  else:
    champ_prediction_bool.append(False)
print(champ_prediction_bool)

[False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

In [ ]:
# push results, values, and rank to team_results df
team_results["Value"] = champ_prediction
team_results["Rank"] = team_results["Value"].rank(method = 'max', ascending = False)
team_results["Champion"] = champ_prediction_bool

team_results = team_results.sort_values(by = ["Rank"])
team_results.set_index("Rank")

      Year                    Team     Value  Champion
Rank
1.0   2019         Milwaukee Bucks  0.165246      True
2.0   2019         Toronto Raptors  0.150467     False
3.0   2019      Los Angeles Lakers  0.145210     False
4.0   2019      Philadelphia 76ers  0.136805     False
5.0   2019          Indiana Pacers  0.120379     False
6.0   2019          Boston Celtics  0.114760     False
7.0   2019              Miami Heat  0.111580     False
8.0   2019       San Antonio Spurs  0.110935     False
9.0   2019  Portland Trail Blazers  0.107636     False
10.0  2019               Utah Jazz  0.089472     False
11.0  2019   Oklahoma City Thunder  0.082744     False
12.0  2019            Phoenix Suns  0.081601     False
13.0  2019    Los Angeles Clippers  0.078474     False
14.0  2019    New Orleans Pelicans  0.077413     False
15.0  2019        Dallas Mavericks  0.065139     False
16.0  2019       Memphis Grizzlies  0.062046     False
17.0  2019          Denver Nuggets  0.054467     False
18.0  2019           Chicago Bulls  0.044924     False
19.0  2019      Washington Wizards  0.019197     False
20.0  2019           Orlando Magic  0.017360     False
21.0  2019        Sacramento Kings  0.004944     False
22.0  2019           Atlanta Hawks  0.001178     False
23.0  2019         Houston Rockets -0.000201     False
24.0  2019         Detroit Pistons -0.000698     False
25.0  2019           Brooklyn Nets -0.003752     False
26.0  2019         New York Knicks -0.012066     False
27.0  2019   Golden State Warriors -0.017440     False
28.0  2019     Cleveland Cavaliers -0.024491     False
29.0  2019  Minnesota Timberwolves -0.027664     False
30.0  2019       Charlotte Hornets -0.029370     False

In [ ]:
from google.colab import files
team_results.to_csv('linear_champ_results.csv')
#files.download('linear_champ_results.csv')

### Neural Network Model Machine Learning

In [ ]:
# convert effect dfs to categroical using tensorflow
from tensorflow.keras.utils import to_categorical
team_champ_train_categorical = to_categorical(team_champ_train_values)
team_champ_test_categorical = to_categorical(team_champ_test_values)

In [ ]:
# set up model and layers for neural network
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# build nueral network
model = Sequential()
model.add(Dense(units=200, activation='relu', input_dim=24))
model.add(Dense(units=200, activation='relu'))
model.add(Dense(units=200, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 200)               5000
_________________________________________________________________
dense_1 (Dense)              (None, 200)               40200
_________________________________________________________________
dense_2 (Dense)              (None, 200)               40200
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 402
=================================================================
Total params: 85,802
Trainable params: 85,802
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(
    team_X_train,
    team_champ_train_categorical,
    epochs=150,
    shuffle=True,
    verbose=2
)

Epoch 1/150
18/18 - 1s - loss: 135.1550 - accuracy: 0.9134
Epoch 2/150
18/18 - 0s - loss: 61.0342 - accuracy: 0.9099
Epoch 3/150
18/18 - 0s - loss: 49.3980 - accuracy: 0.9099
Epoch 4/150
18/18 - 0s - loss: 33.0423 - accuracy: 0.9311
Epoch 5/150
18/18 - 0s - loss: 45.1297 - accuracy: 0.9664
Epoch 6/150
18/18 - 0s - loss: 25.0036 - accuracy: 0.9134
Epoch 7/150
18/18 - 0s - loss: 23.6532 - accuracy: 0.9099
Epoch 8/150
18/18 - 0s - loss: 26.4980 - accuracy: 0.9664
Epoch 9/150
18/18 - 0s - loss: 28.9907 - accuracy: 0.9134
Epoch 10/150
18/18 - 0s - loss: 19.5679 - accuracy: 0.9134
Epoch 11/150
18/18 - 0s - loss: 19.5459 - accuracy: 0.9664
Epoch 12/150
18/18 - 0s - loss: 19.5855 - accuracy: 0.9081
Epoch 13/150
18/18 - 0s - loss: 20.0234 - accuracy: 0.9134
Epoch 14/150
18/18 - 0s - loss: 49.1373 - accuracy: 0.9134
Epoch 15/150
18/18 - 0s - loss: 32.9434 - accuracy: 0.9276
Epoch 16/150
18/18 - 0s - loss: 18.7615 - accuracy: 0.9664
Epoch 17/150
18/18 - 0s - loss: 11.8318 - accuracy: 0.9134
Epoch 18/150
18/18 - 0s - loss: 16.9340 - accuracy: 0.9664
Epoch 19/150
18/18 - 0s - loss: 8.0898 - accuracy: 0.9170
Epoch 20/150
18/18 - 0s - loss: 11.7661 - accuracy: 0.9664
Epoch 21/150
18/18 - 0s - loss: 6.2482 - accuracy: 0.9134
Epoch 22/150
18/18 - 0s - loss: 5.8736 - accuracy: 0.9099
Epoch 23/150
18/18 - 0s - loss: 10.3579 - accuracy: 0.9664
Epoch 24/150
18/18 - 0s - loss: 3.9844 - accuracy: 0.9099
Epoch 25/150
18/18 - 0s - loss: 4.4921 - accuracy: 0.9664
Epoch 26/150
18/18 - 0s - loss: 3.8260 - accuracy: 0.9099
Epoch 27/150
18/18 - 0s - loss: 2.5083 - accuracy: 0.9134
Epoch 28/150
18/18 - 0s - loss: 1.2366 - accuracy: 0.9099
Epoch 29/150
18/18 - 0s - loss: 2.0119 - accuracy: 0.9664
Epoch 30/150
18/18 - 0s - loss: 0.4140 - accuracy: 0.9664
Epoch 31/150
18/18 - 0s - loss: 0.2807 - accuracy: 0.9664
Epoch 32/150
18/18 - 0s - loss: 2.5453 - accuracy: 0.9205
Epoch 33/150
18/18 - 0s - loss: 1.9399 - accuracy: 0.9099
Epoch 34/150
18/18 - 0s - loss: 1.7930 - accuracy: 0.9346
Epoch 35/150
18/18 - 0s - loss: 2.8730 - accuracy: 0.9664
Epoch 36/150
18/18 - 0s - loss: 2.8372 - accuracy: 0.9134
Epoch 37/150
18/18 - 0s - loss: 2.2526 - accuracy: 0.9664
Epoch 38/150
18/18 - 0s - loss: 1.7755 - accuracy: 0.9170
Epoch 39/150
18/18 - 0s - loss: 2.6994 - accuracy: 0.9099
Epoch 40/150
18/18 - 0s - loss: 4.8621 - accuracy: 0.9205
Epoch 41/150
18/18 - 0s - loss: 5.4101 - accuracy: 0.9134
Epoch 42/150
18/18 - 0s - loss: 7.3000 - accuracy: 0.9099
Epoch 43/150
18/18 - 0s - loss: 6.9093 - accuracy: 0.9664
Epoch 44/150
18/18 - 0s - loss: 1.0887 - accuracy: 0.9134
Epoch 45/150
18/18 - 0s - loss: 1.7731 - accuracy: 0.9664
Epoch 46/150
18/18 - 0s - loss: 0.3655 - accuracy: 0.9664
Epoch 47/150
18/18 - 0s - loss: 0.1891 - accuracy: 0.9664
Epoch 48/150
18/18 - 0s - loss: 0.1678 - accuracy: 0.9664
Epoch 49/150
18/18 - 0s - loss: 0.1763 - accuracy: 0.9664
Epoch 50/150
18/18 - 0s - loss: 0.2298 - accuracy: 0.9664
Epoch 51/150
18/18 - 0s - loss: 0.2231 - accuracy: 0.9664
Epoch 52/150
18/18 - 0s - loss: 0.1745 - accuracy: 0.9664
Epoch 53/150
18/18 - 0s - loss: 0.1793 - accuracy: 0.9664
Epoch 54/150
18/18 - 0s - loss: 0.1591 - accuracy: 0.9664
Epoch 55/150
18/18 - 0s - loss: 0.1483 - accuracy: 0.9664
Epoch 56/150
18/18 - 0s - loss: 0.1650 - accuracy: 0.9664
Epoch 57/150
18/18 - 0s - loss: 0.1504 - accuracy: 0.9664
Epoch 58/150
18/18 - 0s - loss: 0.1744 - accuracy: 0.9664
Epoch 59/150
18/18 - 0s - loss: 0.1748 - accuracy: 0.9664
Epoch 60/150
18/18 - 0s - loss: 3.3536 - accuracy: 0.9134
Epoch 61/150
18/18 - 0s - loss: 5.9743 - accuracy: 0.8640
Epoch 62/150
18/18 - 0s - loss: 16.0224 - accuracy: 0.9664
Epoch 63/150
18/18 - 0s - loss: 4.6958 - accuracy: 0.9134
Epoch 64/150
18/18 - 0s - loss: 3.3613 - accuracy: 0.9099
Epoch 65/150
18/18 - 0s - loss: 2.5877 - accuracy: 0.9170
Epoch 66/150
18/18 - 0s - loss: 4.4331 - accuracy: 0.9664
Epoch 67/150
18/18 - 0s - loss: 2.0475 - accuracy: 0.9134
Epoch 68/150
18/18 - 0s - loss: 2.2481 - accuracy: 0.9134
Epoch 69/150
18/18 - 0s - loss: 1.4039 - accuracy: 0.9664
Epoch 70/150
18/18 - 0s - loss: 0.2702 - accuracy: 0.9664
Epoch 71/150
18/18 - 0s - loss: 0.1706 - accuracy: 0.9664
Epoch 72/150
18/18 - 0s - loss: 0.1511 - accuracy: 0.9664
Epoch 73/150
18/18 - 0s - loss: 0.1674 - accuracy: 0.9664
Epoch 74/150
18/18 - 0s - loss: 0.1811 - accuracy: 0.9664
Epoch 75/150
18/18 - 0s - loss: 0.1825 - accuracy: 0.9664
Epoch 76/150
18/18 - 0s - loss: 0.1534 - accuracy: 0.9664
Epoch 77/150
18/18 - 0s - loss: 0.1514 - accuracy: 0.9664
Epoch 78/150
18/18 - 0s - loss: 0.1597 - accuracy: 0.9664
Epoch 79/150
18/18 - 0s - loss: 0.1667 - accuracy: 0.9664
Epoch 80/150
18/18 - 0s - loss: 0.1502 - accuracy: 0.9664
Epoch 81/150
18/18 - 0s - loss: 0.1627 - accuracy: 0.9664
Epoch 82/150
18/18 - 0s - loss: 0.1581 - accuracy: 0.9664
Epoch 83/150
18/18 - 0s - loss: 0.1489 - accuracy: 0.9664
Epoch 84/150
18/18 - 0s - loss: 0.1576 - accuracy: 0.9664
Epoch 85/150
18/18 - 0s - loss: 0.1531 - accuracy: 0.9664
Epoch 86/150
18/18 - 0s - loss: 0.1576 - accuracy: 0.9664
Epoch 87/150
18/18 - 0s - loss: 0.1483 - accuracy: 0.9664
Epoch 88/150
18/18 - 0s - loss: 0.1655 - accuracy: 0.9664
Epoch 89/150
18/18 - 0s - loss: 0.1592 - accuracy: 0.9664
Epoch 90/150
18/18 - 0s - loss: 0.1524 - accuracy: 0.9664
Epoch 91/150
18/18 - 0s - loss: 0.1571 - accuracy: 0.9664
Epoch 92/150
18/18 - 0s - loss: 0.1505 - accuracy: 0.9664
Epoch 93/150
18/18 - 0s - loss: 0.1531 - accuracy: 0.9664
Epoch 94/150
18/18 - 0s - loss: 0.1507 - accuracy: 0.9664
Epoch 95/150
18/18 - 0s - loss: 0.1570 - accuracy: 0.9664
Epoch 96/150
18/18 - 0s - loss: 0.1517 - accuracy: 0.9664
Epoch 97/150
18/18 - 0s - loss: 0.1489 - accuracy: 0.9664
Epoch 98/150
18/18 - 0s - loss: 0.1505 - accuracy: 0.9664
Epoch 99/150
18/18 - 0s - loss: 0.1532 - accuracy: 0.9664
Epoch 100/150
18/18 - 0s - loss: 0.1525 - accuracy: 0.9664
Epoch 101/150
18/18 - 0s - loss: 0.1530 - accuracy: 0.9664
Epoch 102/150
18/18 - 0s - loss: 0.1771 - accuracy: 0.9664
Epoch 103/150
18/18 - 0s - loss: 0.1836 - accuracy: 0.9664
Epoch 104/150
18/18 - 0s - loss: 0.1755 - accuracy: 0.9664
Epoch 105/150
18/18 - 0s - loss: 0.1601 - accuracy: 0.9664
Epoch 106/150
18/18 - 0s - loss: 0.1524 - accuracy: 0.9664
Epoch 107/150
18/18 - 0s - loss: 0.1621 - accuracy: 0.9664
Epoch 108/150
18/18 - 0s - loss: 0.1511 - accuracy: 0.9664
Epoch 109/150
18/18 - 0s - loss: 0.1557 - accuracy: 0.9664
Epoch 110/150
18/18 - 0s - loss: 0.1733 - accuracy: 0.9664
Epoch 111/150
18/18 - 0s - loss: 0.1676 - accuracy: 0.9664
Epoch 112/150
18/18 - 0s - loss: 0.1543 - accuracy: 0.9664
Epoch 113/150
18/18 - 0s - loss: 0.1673 - accuracy: 0.9664
Epoch 114/150
18/18 - 0s - loss: 0.1577 - accuracy: 0.9664
Epoch 115/150
18/18 - 0s - loss: 0.1680 - accuracy: 0.9664
Epoch 116/150
18/18 - 0s - loss: 0.1634 - accuracy: 0.9664
Epoch 117/150
18/18 - 0s - loss: 0.1906 - accuracy: 0.9664
Epoch 118/150
18/18 - 0s - loss: 0.1553 - accuracy: 0.9664
Epoch 119/150
18/18 - 0s - loss: 0.1552 - accuracy: 0.9664
Epoch 120/150
18/18 - 0s - loss: 0.1562 - accuracy: 0.9664
Epoch 121/150
18/18 - 0s - loss: 0.1552 - accuracy: 0.9664
Epoch 122/150
18/18 - 0s - loss: 0.1561 - accuracy: 0.9664
Epoch 123/150
18/18 - 0s - loss: 0.1589 - accuracy: 0.9664
Epoch 124/150
18/18 - 0s - loss: 0.1532 - accuracy: 0.9664
Epoch 125/150
18/18 - 0s - loss: 0.1538 - accuracy: 0.9664
Epoch 126/150
18/18 - 0s - loss: 0.1552 - accuracy: 0.9664
Epoch 127/150
18/18 - 0s - loss: 0.1566 - accuracy: 0.9664
Epoch 128/150
18/18 - 0s - loss: 0.1493 - accuracy: 0.9664
Epoch 129/150
18/18 - 0s - loss: 0.1598 - accuracy: 0.9664
Epoch 130/150
18/18 - 0s - loss: 0.1508 - accuracy: 0.9664
Epoch 131/150
18/18 - 0s - loss: 0.1564 - accuracy: 0.9664
Epoch 132/150
18/18 - 0s - loss: 0.1497 - accuracy: 0.9664
Epoch 133/150
18/18 - 0s - loss: 0.1535 - accuracy: 0.9664
Epoch 134/150
18/18 - 0s - loss: 0.1579 - accuracy: 0.9664
Epoch 135/150
18/18 - 0s - loss: 0.1497 - accuracy: 0.9664
Epoch 136/150
18/18 - 0s - loss: 0.1505 - accuracy: 0.9664
Epoch 137/150
18/18 - 0s - loss: 0.1497 - accuracy: 0.9664
Epoch 138/150
18/18 - 0s - loss: 0.1564 - accuracy: 0.9664
Epoch 139/150
18/18 - 0s - loss: 0.1591 - accuracy: 0.9664
Epoch 140/150
18/18 - 0s - loss: 0.1508 - accuracy: 0.9664
Epoch 141/150
18/18 - 0s - loss: 0.1502 - accuracy: 0.9664
Epoch 142/150
18/18 - 0s - loss: 0.1511 - accuracy: 0.9664
Epoch 143/150
18/18 - 0s - loss: 0.1516 - accuracy: 0.9664
Epoch 144/150
18/18 - 0s - loss: 0.1520 - accuracy: 0.9664
Epoch 145/150
18/18 - 0s - loss: 0.1922 - accuracy: 0.9664
Epoch 146/150
18/18 - 0s - loss: 0.1512 - accuracy: 0.9664
Epoch 147/150
18/18 - 0s - loss: 0.1534 - accuracy: 0.9664
Epoch 148/150
18/18 - 0s - loss: 0.1695 - accuracy: 0.9664
Epoch 149/150
18/18 - 0s - loss: 0.1491 - accuracy: 0.9664
Epoch 150/150
18/18 - 0s - loss: 0.1529 - accuracy: 0.9664

In [ ]:
 # use predicted values for true
 encoded_predictions = model.predict_proba(team_X_test)
 print(encoded_predictions)

[[0.9446469  0.05535307]
 [0.93929994 0.06070006]
 [0.94140506 0.05859496]
 [0.93813795 0.0618621 ]
 [0.9374947  0.06250528]
 [0.93817043 0.06182953]
 [0.93933296 0.06066707]
 [0.9369162  0.06308381]
 [0.9399564  0.06004358]
 [0.9389072  0.06109283]
 [0.9409418  0.05905821]
 [0.94154227 0.05845773]
 [0.9368494  0.06315052]
 [0.9356632  0.06433685]
 [0.93912077 0.06087923]
 [0.9350132  0.0649868 ]
 [0.93959063 0.06040938]
 [0.9367222  0.0632778 ]
 [0.9409325  0.05906751]
 [0.9383371  0.06166293]
 [0.93834096 0.061659  ]
 [0.9393923  0.06060763]
 [0.9286547  0.0713454 ]
 [0.91872036 0.08127965]
 [0.92431706 0.0756829 ]
 [0.9229434  0.07705654]
 [0.9223241  0.07767589]
 [0.9216385  0.0783615 ]
 [0.92181146 0.07818855]
 [0.9221561  0.07784384]]

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:425: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '

In [ ]:
values = []
for x in encoded_predictions:
  values.append(x[1])
print(values)

[0.05535307, 0.060700063, 0.05859496, 0.061862096, 0.06250528, 0.061829526, 0.06066707, 0.06308381, 0.06004358, 0.061092827, 0.059058208, 0.058457732, 0.06315052, 0.06433685, 0.06087923, 0.064986795, 0.06040938, 0.063277796, 0.05906751, 0.061662927, 0.061659, 0.060607634, 0.071345404, 0.08127965, 0.0756829, 0.07705654, 0.07767589, 0.0783615, 0.07818855, 0.077843845]

In [ ]:
team_results2["Value"] = values
team_results2["Rank"] = team_results2["Value"].rank(method = 'max', ascending = False)
team_results2 = team_results2.sort_values(by = ["Rank"])
team_results2 = team_results2.set_index("Rank")

In [ ]:
team_results2

      Year                    Team     Value
Rank
1.0   2019           Brooklyn Nets  0.081280
2.0   2019  Portland Trail Blazers  0.078361
3.0   2019          Denver Nuggets  0.078189
4.0   2019        Dallas Mavericks  0.077844
5.0   2019              Miami Heat  0.077676
6.0   2019          Indiana Pacers  0.077057
7.0   2019       Memphis Grizzlies  0.075683
8.0   2019           Orlando Magic  0.071345
9.0   2019    New Orleans Pelicans  0.064987
10.0  2019    Los Angeles Clippers  0.064337
11.0  2019        Sacramento Kings  0.063278
12.0  2019      Washington Wizards  0.063151
13.0  2019           Atlanta Hawks  0.063084
14.0  2019     Cleveland Cavaliers  0.062505
15.0  2019       Charlotte Hornets  0.061862
16.0  2019         New York Knicks  0.061830
17.0  2019      Philadelphia 76ers  0.061663
18.0  2019         Milwaukee Bucks  0.061659
19.0  2019       San Antonio Spurs  0.061093
20.0  2019         Houston Rockets  0.060879
21.0  2019           Chicago Bulls  0.060700
22.0  2019         Detroit Pistons  0.060667
23.0  2019            Phoenix Suns  0.060608
24.0  2019   Oklahoma City Thunder  0.060409
25.0  2019      Los Angeles Lakers  0.060044
26.0  2019          Boston Celtics  0.059068
27.0  2019               Utah Jazz  0.059058
28.0  2019   Golden State Warriors  0.058595
29.0  2019         Toronto Raptors  0.058458
30.0  2019  Minnesota Timberwolves  0.055353

In [ ]:
team_X_test["Values"] = values
team_X_test["Team"] = team_encoder.inverse_transform(team_X_test["Team"])
team_X_test

                       Team   G     MP    FG  ...   TOV    PF    PTS    Values
566        Dallas Mavericks  75  18175  41.5  ...  12.7  19.4  116.7  0.055353
567         Milwaukee Bucks  73  17595  41.0  ...  14.3  18.6  112.4  0.060700
568  Portland Trail Blazers  74  17835  41.7  ...  12.6  21.5  113.7  0.058595
569         Houston Rockets  72  17380  39.1  ...  14.1  20.8  112.9  0.061862
570    Los Angeles Clippers  72  17380  40.7  ...  14.3  21.7  113.9  0.062505
571    New Orleans Pelicans  72  17430  40.7  ...  15.7  20.2  110.7  0.061830
572            Phoenix Suns  73  17595  40.5  ...  14.5  21.7  111.7  0.060667
573      Washington Wizards  72  17355  40.3  ...  13.7  22.0  110.9  0.063084
574       Memphis Grizzlies  73  17570  41.3  ...  14.8  20.5  109.2  0.060044
575          Boston Celtics  72  17430  41.1  ...  13.8  21.5  113.3  0.061093
576              Miami Heat  73  17745  39.6  ...  15.0  20.6  112.5  0.059058
577          Denver Nuggets  73  17745  42.7  ...  14.0  20.7  113.1  0.058458
578         Toronto Raptors  72  17380  39.6  ...  14.6  21.3  111.1  0.063151
579       San Antonio Spurs  71  17215  41.6  ...  12.4  19.1  112.4  0.064337
580      Philadelphia 76ers  73  17595  41.3  ...  14.3  21.1  111.3  0.060879
581      Los Angeles Lakers  71  17090  41.8  ...  15.0  20.5  112.0  0.064987
582           Brooklyn Nets  72  17480  39.4  ...  14.9  20.4  108.9  0.060409
583               Utah Jazz  72  17355  40.5  ...  15.3  20.6  112.3  0.063278
584          Indiana Pacers  73  17620  42.3  ...  13.3  19.9  110.0  0.059068
585   Oklahoma City Thunder  72  17430  40.1  ...  13.7  19.4  110.8  0.061663
586        Sacramento Kings  72  17455  40.9  ...  14.5  22.2  110.2  0.061659
587           Orlando Magic  73  17570  39.8  ...  13.0  18.5  108.5  0.060608
588           Atlanta Hawks  67  16280  39.0  ...  15.5  22.2  107.2  0.071345
589  Minnesota Timberwolves  64  15560  38.6  ...  14.6  20.4  108.1  0.081280
590         Detroit Pistons  66  15965  40.0  ...  15.5  20.0  109.0  0.075683
591         New York Knicks  66  15965  40.2  ...  14.4  22.3  106.5  0.077057
592     Cleveland Cavaliers  65  15725  40.5  ...  16.6  18.4  107.5  0.077676
593           Chicago Bulls  65  15675  39.5  ...  15.4  21.8  106.7  0.078361
594   Golden State Warriors  65  15725  38.2  ...  14.7  19.8  105.2  0.078189
595       Charlotte Hornets  65  15750  38.6  ...  15.1  19.5  106.3  0.077844

[30 rows x 25 columns]

In [ ]:
team_X_test

                       Team   G     MP    FG  ...   TOV    PF    PTS    Values
566        Dallas Mavericks  75  18175  41.5  ...  12.7  19.4  116.7  0.055353
567         Milwaukee Bucks  73  17595  41.0  ...  14.3  18.6  112.4  0.060700
568  Portland Trail Blazers  74  17835  41.7  ...  12.6  21.5  113.7  0.058595
569         Houston Rockets  72  17380  39.1  ...  14.1  20.8  112.9  0.061862
570    Los Angeles Clippers  72  17380  40.7  ...  14.3  21.7  113.9  0.062505
571    New Orleans Pelicans  72  17430  40.7  ...  15.7  20.2  110.7  0.061830
572            Phoenix Suns  73  17595  40.5  ...  14.5  21.7  111.7  0.060667
573      Washington Wizards  72  17355  40.3  ...  13.7  22.0  110.9  0.063084
574       Memphis Grizzlies  73  17570  41.3  ...  14.8  20.5  109.2  0.060044
575          Boston Celtics  72  17430  41.1  ...  13.8  21.5  113.3  0.061093
576              Miami Heat  73  17745  39.6  ...  15.0  20.6  112.5  0.059058
577          Denver Nuggets  73  17745  42.7  ...  14.0  20.7  113.1  0.058458
578         Toronto Raptors  72  17380  39.6  ...  14.6  21.3  111.1  0.063151
579       San Antonio Spurs  71  17215  41.6  ...  12.4  19.1  112.4  0.064337
580      Philadelphia 76ers  73  17595  41.3  ...  14.3  21.1  111.3  0.060879
581      Los Angeles Lakers  71  17090  41.8  ...  15.0  20.5  112.0  0.064987
582           Brooklyn Nets  72  17480  39.4  ...  14.9  20.4  108.9  0.060409
583               Utah Jazz  72  17355  40.5  ...  15.3  20.6  112.3  0.063278
584          Indiana Pacers  73  17620  42.3  ...  13.3  19.9  110.0  0.059068
585   Oklahoma City Thunder  72  17430  40.1  ...  13.7  19.4  110.8  0.061663
586        Sacramento Kings  72  17455  40.9  ...  14.5  22.2  110.2  0.061659
587           Orlando Magic  73  17570  39.8  ...  13.0  18.5  108.5  0.060608
588           Atlanta Hawks  67  16280  39.0  ...  15.5  22.2  107.2  0.071345
589  Minnesota Timberwolves  64  15560  38.6  ...  14.6  20.4  108.1  0.081280
590         Detroit Pistons  66  15965  40.0  ...  15.5  20.0  109.0  0.075683
591         New York Knicks  66  15965  40.2  ...  14.4  22.3  106.5  0.077057
592     Cleveland Cavaliers  65  15725  40.5  ...  16.6  18.4  107.5  0.077676
593           Chicago Bulls  65  15675  39.5  ...  15.4  21.8  106.7  0.078361
594   Golden State Warriors  65  15725  38.2  ...  14.7  19.8  105.2  0.078189
595       Charlotte Hornets  65  15750  38.6  ...  15.1  19.5  106.3  0.077844

[30 rows x 25 columns]

In [ ]:
from google.colab import files
team_X_test.to_csv('neural_champ_results.csv')
files.download('neural_champ_results.csv')